language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script: 
  -npm run lint
  - npm run test 
after_success:
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls